version: "3.5"
services:
  db:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=rinha-backend
    ports:
      - "27017:27017"
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "0.9GB"
    networks:
      - rinha-node

  cache:
    hostname: cache
    image: redis:latest
    ports:
      - "6379:6379"
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "0.5GB"
    networks:
      - rinha-node

  api1:
    # API - Instância 01
    # image: giobassetto/rinha-node:latest
    build: .
    hostname: api1
    depends_on:
      - db
      - cache
    environment:
      - DATABASE_URL=mongodb://root:root@db:27017/rinha-backend?authSource=admin&retryWrites=true&w=majority
      - REDIS_PORT=6379
      - REDIS_HOST=cache
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "0.75GB"
    networks:
      - rinha-node

  api2:
    # API - Instância 02
    build: .
    hostname: api2
    depends_on:
      - db
      - cache
    environment:
      - DATABASE_URL=mongodb://root:root@db:27017/rinha-backend?authSource=admin&retryWrites=true&w=majority
      - REDIS_PORT=6379
      - REDIS_HOST=cache
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "0.75GB"
    networks:
      - rinha-node

  nginx:
    # Load Balancer
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "0.2GB"
    networks:
      - rinha-node
networks:
  rinha-node:
